[package]
name = "benchmark-rust-rhai"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rhai = "1.22.2"
plotly = "0.12.1"
